from jeu.epreuve import Epreuve
from jeu.partie import Partie
from jeu.personnage import Personnage
from jeu.tournoi_trois_sorciers import TournoiTroisSorciers
from jeu.sorcier import Sorcier
from jeu.lancer_expeliarmus import LancerExpeliarmus
from jeu.lancer_expecto_patronum import LancerExpectoPatronum
from jeu.lancer_avada_kedavra import LancerAvadaKeavra
from jeu.sorcier_gris import SorcierGris